const itemIconCatalog = [
	{
		id: "generic",
		parents: [],
		identityTerms: [],
		categoryTerms: ["generic", "misc", "miscellaneous", "other", "unknown", "object"],
	},
	{
		id: "toy-and-game",
		parents: [],
		identityTerms: [
			"toy",
			"plaything",
			"doll",
			"dice",
			"cards",
			"game piece",
			"ball",
			"tennis ball",
			"squeaky toy",
			"rubber toy",
			"dog toy",
			"rope toy",
		],
		categoryTerms: ["game"],
	},
	{
		id: "vehicle",
		parents: [],
		identityTerms: ["vehicle", "cart", "wagon", "carriage", "chariot", "van", "truck"],
		categoryTerms: ["transport"],
	},
	{
		id: "boat",
		parents: ["vehicle"],
		identityTerms: ["boat", "ship", "watercraft", "canoe", "raft", "skiff", "barge"],
		categoryTerms: [],
	},
	{
		id: "structure",
		parents: [],
		identityTerms: ["building", "edifice", "fixture"],
		categoryTerms: ["structure", "architecture", "construction"],
	},
	{
		id: "fortification",
		parents: ["structure"],
		identityTerms: [
			"wall",
			"tower",
			"watchtower",
			"rampart",
			"battlement",
			"fortress",
			"barricade",
			"fence",
			"palisade",
			"railing",
		],
		categoryTerms: ["fortification"],
	},
	{
		id: "bridge",
		parents: ["structure"],
		identityTerms: ["bridge", "crossing", "footbridge", "drawbridge", "causeway", "gangway"],
		categoryTerms: [],
	},
	{
		id: "stairs",
		parents: ["structure"],
		identityTerms: ["stairs", "staircase", "steps", "ladder", "ramp", "escalator"],
		categoryTerms: [],
	},
	{
		id: "well-and-fountain",
		parents: ["structure"],
		identityTerms: [
			"well",
			"fountain",
			"spring",
			"cistern",
			"water pump",
			"basin",
			"hydrant",
			"fire hydrant",
			"fireplug",
			"sprinkler",
			"lawn sprinkler",
		],
		categoryTerms: ["water source"],
	},
	{
		id: "door",
		parents: ["structure"],
		identityTerms: ["door", "doorway", "entrance", "exit", "threshold", "barrier"],
		categoryTerms: [],
	},
	{
		id: "gate",
		parents: ["door"],
		identityTerms: ["gate", "portcullis", "wicket", "turnstile", "gateway", "grille"],
		categoryTerms: [],
	},
	{
		id: "hatch",
		parents: ["door"],
		identityTerms: [
			"hatch",
			"trapdoor",
			"cellar door",
			"manhole",
			"bulkhead",
			"access panel",
			"storm drain",
			"sewer grate",
			"grate",
		],
		categoryTerms: [],
	},
	{
		id: "portal",
		parents: ["door"],
		identityTerms: ["portal", "teleporter", "rift", "wormhole", "waygate", "magic door"],
		categoryTerms: [],
	},
	{
		id: "furniture",
		parents: [],
		identityTerms: ["furniture", "furnishing"],
		categoryTerms: ["household", "interior"],
		descriptorTerms: ["decor"],
	},
	{
		id: "seat",
		parents: ["furniture"],
		identityTerms: ["chair", "seat", "stool", "bench", "sofa", "couch", "throne"],
		categoryTerms: [],
	},
	{
		id: "table",
		parents: ["furniture"],
		identityTerms: ["table", "desk", "counter", "workbench", "altar table", "dining table"],
		categoryTerms: [],
	},
	{
		id: "bed",
		parents: ["furniture"],
		identityTerms: ["bed", "cot", "bunk", "hammock", "mattress", "bedroll", "dog bed"],
		categoryTerms: [],
	},
	{
		id: "shelf-and-cabinet",
		parents: ["furniture"],
		identityTerms: ["shelf", "shelves", "cabinet", "cupboard", "wardrobe", "bookcase", "dresser"],
		categoryTerms: ["storage furniture"],
	},
	{
		id: "container",
		parents: [],
		identityTerms: ["container", "storage", "receptacle", "vessel"],
		categoryTerms: [],
	},
	{
		id: "chest",
		parents: ["container"],
		identityTerms: ["chest", "coffer", "trunk", "lockbox", "crate", "treasure chest"],
		categoryTerms: [],
	},
	{
		id: "barrel",
		parents: ["container"],
		identityTerms: ["barrel", "cask", "keg", "oil drum", "vat", "tub"],
		categoryTerms: [],
	},
	{
		id: "bag",
		parents: ["container"],
		identityTerms: ["bag", "sack", "pouch", "backpack", "satchel", "purse", "packet"],
		categoryTerms: [],
	},
	{
		id: "bottle",
		parents: ["container"],
		identityTerms: ["bottle", "flask", "jar", "vial", "jug", "can", "canteen", "spray bottle"],
		categoryTerms: [],
	},
	{
		id: "cage",
		parents: ["container"],
		identityTerms: [
			"cage",
			"kennel",
			"crate cage",
			"animal pen",
			"livestock pen",
			"enclosure",
			"jail",
			"cell",
		],
		categoryTerms: [],
	},
	{
		id: "mechanism",
		parents: [],
		identityTerms: ["mechanism", "machine", "device", "clockwork", "gear", "apparatus"],
		categoryTerms: [],
	},
	{
		id: "control",
		parents: ["mechanism"],
		identityTerms: ["lever", "switch", "button", "dial", "crank", "valve", "control panel"],
		categoryTerms: ["control"],
	},
	{
		id: "clock",
		parents: ["mechanism"],
		identityTerms: ["clock", "watch", "timer", "hourglass", "sundial", "timepiece", "alarm clock"],
		categoryTerms: [],
	},
	{
		id: "trap",
		parents: ["mechanism"],
		identityTerms: ["trap", "snare", "tripwire", "pressure plate", "pitfall", "trigger", "hazard"],
		categoryTerms: [],
	},
	{
		id: "lock",
		parents: ["mechanism"],
		identityTerms: ["lock", "padlock", "combination lock", "latch", "deadbolt", "seal"],
		categoryTerms: [],
	},
	{
		id: "engine",
		parents: ["mechanism"],
		identityTerms: ["engine", "motor", "generator", "turbine", "pump", "power unit"],
		categoryTerms: [],
	},
	{
		id: "tool",
		parents: [],
		identityTerms: ["tool", "implement", "utensil", "equipment", "gear"],
		categoryTerms: [],
	},
	{
		id: "hammer",
		parents: ["tool"],
		identityTerms: ["hammer", "mallet", "sledge", "gavel", "maul", "tack hammer"],
		categoryTerms: [],
	},
	{
		id: "rope",
		parents: ["tool"],
		identityTerms: ["rope", "cord", "twine", "tether", "wire", "hose", "garden hose"],
		categoryTerms: [],
	},
	{
		id: "writing-tool",
		parents: ["tool"],
		identityTerms: [
			"quill",
			"pen",
			"fountain pen",
			"ink",
			"inkwell",
			"chalk",
			"stylus",
			"writing tool",
		],
		categoryTerms: [],
	},
	{
		id: "cooking-tool",
		parents: ["tool"],
		identityTerms: ["cookware", "pan", "pot", "cauldron", "ladle", "spatula", "kitchen tool"],
		categoryTerms: [],
	},
	{
		id: "medical-tool",
		parents: ["tool"],
		identityTerms: [
			"medicine",
			"bandage",
			"salve",
			"medical kit",
			"syringe",
			"antidote",
			"healing kit",
		],
		categoryTerms: ["medical tool"],
	},
	{
		id: "navigation-tool",
		parents: ["tool"],
		identityTerms: ["compass", "sextant", "telescope", "spyglass", "astrolabe", "navigation tool"],
		categoryTerms: ["navigation"],
	},
	{
		id: "key",
		parents: [],
		identityTerms: ["key", "skeleton key", "lockpick", "latchkey", "keyring", "unlocker"],
		categoryTerms: [],
	},
	{
		id: "credential",
		parents: ["key"],
		identityTerms: ["keycard", "pass", "permit", "ticket", "badge", "token", "invitation"],
		categoryTerms: ["credential"],
	},
	{
		id: "weapon",
		parents: [],
		identityTerms: [
			"weapon",
			"arms",
			"armament",
			"spear",
			"polearm",
			"lance",
			"pike",
			"halberd",
			"trident",
			"javelin",
		],
		categoryTerms: ["combat weapon"],
		descriptorTerms: ["offensive"],
	},
	{
		id: "blade",
		parents: ["weapon"],
		identityTerms: ["sword", "blade", "rapier", "saber", "scimitar", "longsword", "shortsword"],
		categoryTerms: [],
	},
	{
		id: "axe",
		parents: ["weapon"],
		identityTerms: ["axe", "hatchet", "battleaxe", "tomahawk", "handaxe"],
		categoryTerms: [],
	},
	{
		id: "bow",
		parents: ["weapon"],
		identityTerms: ["bow", "crossbow", "sling", "slingshot", "arrow", "bolt", "quiver"],
		categoryTerms: [],
	},
	{
		id: "knife",
		parents: ["weapon"],
		identityTerms: [
			"knife",
			"dagger",
			"cleaver",
			"dirk",
			"pocketknife",
			"kitchen knife",
			"butcher knife",
			"ritual knife",
			"athame",
		],
		categoryTerms: [],
	},
	{
		id: "blunt-weapon",
		parents: ["weapon"],
		identityTerms: ["club", "mace", "flail", "cudgel", "baton", "morning star", "morningstar"],
		categoryTerms: ["blunt weapon"],
	},
	{
		id: "firearm",
		parents: ["weapon"],
		identityTerms: ["firearm", "gun", "pistol", "rifle", "musket", "cannon", "blaster"],
		categoryTerms: [],
	},
	{
		id: "shield",
		parents: ["weapon"],
		identityTerms: ["shield", "buckler", "kite shield", "tower shield", "defender", "guard"],
		categoryTerms: [],
	},
	{
		id: "wearable",
		parents: [],
		identityTerms: ["wearable", "clothing", "garment", "apparel", "attire", "outfit"],
		categoryTerms: [],
	},
	{
		id: "armor",
		parents: ["wearable"],
		identityTerms: ["armor", "armour", "mail", "chainmail", "breastplate", "plate", "cuirass"],
		categoryTerms: [],
	},
	{
		id: "headwear",
		parents: ["wearable"],
		identityTerms: ["helmet", "hat", "cap", "hood", "headwear"],
		categoryTerms: [],
	},
	{
		id: "footwear",
		parents: ["wearable"],
		identityTerms: ["boots", "shoes", "sandals", "slippers", "greaves", "footwear"],
		categoryTerms: [],
	},
	{
		id: "gloves",
		parents: ["wearable"],
		identityTerms: ["gloves", "gauntlets", "mittens", "bracers", "handwear", "hand armor"],
		categoryTerms: [],
	},
	{
		id: "cloak",
		parents: ["wearable"],
		identityTerms: ["cloak", "cape", "robe", "coat", "mantle", "shawl", "tunic"],
		categoryTerms: [],
	},
	{
		id: "mask",
		parents: ["wearable"],
		identityTerms: ["mask", "veil", "disguise", "costume", "goggles", "blindfold", "face covering"],
		categoryTerms: [],
	},
	{
		id: "light",
		parents: [],
		identityTerms: [
			"light",
			"lamp",
			"lantern",
			"candle",
			"taper",
			"candlestick",
			"candelabra",
			"wax light",
			"votive",
		],
		categoryTerms: ["illumination"],
		descriptorTerms: ["luminous", "glow"],
	},
	{
		id: "torch",
		parents: ["light"],
		identityTerms: ["torch", "brand", "flare", "flashlight", "hand light", "rushlight"],
		categoryTerms: [],
	},
	{
		id: "chain-and-link",
		parents: ["tool"],
		identityTerms: ["chain", "link", "shackle", "manacle", "cable", "chain link", "metal chain"],
		categoryTerms: [],
	},
	{
		id: "fire",
		parents: ["light"],
		identityTerms: ["fire", "campfire", "bonfire", "hearth", "fireplace", "brazier", "ember"],
		categoryTerms: [],
	},
	{
		id: "document",
		parents: [],
		identityTerms: [
			"document",
			"text",
			"writing",
			"record",
			"paper",
			"manuscript",
			"scroll",
			"parchment",
			"papyrus",
			"decree",
			"proclamation",
			"certificate",
		],
		categoryTerms: [],
	},
	{
		id: "book",
		parents: ["document"],
		identityTerms: ["book", "tome", "codex", "manual", "volume", "journal", "diary"],
		categoryTerms: [],
	},
	{
		id: "explosive",
		parents: ["mechanism"],
		identityTerms: [
			"bomb",
			"explosive",
			"dynamite",
			"grenade",
			"powder keg",
			"firework",
			"blasting charge",
		],
		categoryTerms: [],
	},
	{
		id: "map",
		parents: ["document"],
		identityTerms: ["map", "chart", "atlas", "blueprint", "plan", "diagram", "schematic"],
		categoryTerms: [],
	},
	{
		id: "letter",
		parents: ["document"],
		identityTerms: ["letter", "note", "message", "correspondence", "telegram", "memo", "mail"],
		categoryTerms: [],
	},
	{
		id: "food",
		parents: [],
		identityTerms: ["food", "nourishment", "ration", "ingredient"],
		categoryTerms: [],
		descriptorTerms: ["edible", "consumable"],
	},
	{
		id: "produce",
		parents: ["food"],
		identityTerms: [
			"fruit",
			"vegetable",
			"berry",
			"apple",
			"carrot",
			"grain",
			"melon",
			"watermelon",
			"produce",
		],
		categoryTerms: [],
	},
	{
		id: "bread-and-pastry",
		parents: ["food"],
		identityTerms: ["bread", "loaf", "pastry", "cake", "biscuit", "pie"],
		categoryTerms: [],
		descriptorTerms: ["baked"],
	},
	{
		id: "meal",
		parents: ["food"],
		identityTerms: ["meal", "meat", "fish", "stew", "soup", "dish"],
		categoryTerms: [],
		descriptorTerms: ["cooked"],
	},
	{
		id: "drink",
		parents: ["food"],
		identityTerms: ["drink", "beverage", "wine", "ale", "beer", "tea", "juice"],
		categoryTerms: [],
	},
	{
		id: "nature",
		parents: [],
		identityTerms: [
			"nature",
			"plant",
			"flora",
			"wilderness",
			"hedge",
			"bush",
			"soil",
			"dirt",
			"earth",
			"ground",
		],
		categoryTerms: [],
		descriptorTerms: ["natural", "organic"],
	},
	{
		id: "wood-and-tree",
		parents: ["nature"],
		identityTerms: ["tree", "wood", "timber", "branch", "log", "root", "bark", "stick", "driftwood"],
		categoryTerms: [],
	},
	{
		id: "herb-and-flower",
		parents: ["nature"],
		identityTerms: ["herb", "flower", "blossom", "leaf", "seed", "grass", "vine"],
		categoryTerms: [],
	},
	{
		id: "fungus",
		parents: ["nature"],
		identityTerms: ["fungus", "mushroom", "toadstool", "mold", "lichen", "spore"],
		categoryTerms: [],
	},
	{
		id: "stone-and-mineral",
		parents: ["nature"],
		identityTerms: ["pebble", "boulder", "rock cluster", "ore deposit", "clay lump"],
		categoryTerms: ["stone", "rock", "mineral", "ore", "clay"],
	},
	{
		id: "fauna",
		parents: ["nature"],
		identityTerms: ["animal", "creature", "beast", "pet", "dog", "cat", "bird", "rabbit", "squirrel"],
		categoryTerms: ["fauna"],
	},
	{
		id: "remains",
		parents: [],
		identityTerms: [
			"remains",
			"corpse",
			"body",
			"cadaver",
			"carcass",
			"mummy",
			"deceased",
			"mortal remains",
		],
		categoryTerms: [],
		descriptorTerms: ["death", "dead", "macabre"],
	},
	{
		id: "fishing-tool",
		parents: ["tool"],
		identityTerms: [
			"fishing rod",
			"fishing hook",
			"fishing line",
			"net",
			"angling gear",
			"tackle",
			"fish trap",
		],
		categoryTerms: ["fishing tool"],
	},
	{
		id: "bone",
		parents: ["remains"],
		identityTerms: ["bone", "bones", "tooth", "fang", "antler", "rawhide", "skeletal"],
		categoryTerms: [],
	},
	{
		id: "grave",
		parents: ["remains"],
		identityTerms: ["grave", "tomb", "coffin", "sarcophagus", "urn", "headstone", "crypt"],
		categoryTerms: [],
	},
	{
		id: "art",
		parents: [],
		identityTerms: ["art", "artwork", "drawing", "chalk drawing", "hopscotch"],
		categoryTerms: ["decoration", "ornament", "display piece"],
		descriptorTerms: ["decorative"],
	},
	{
		id: "painting",
		parents: ["art"],
		identityTerms: ["painting", "portrait", "mural", "picture", "canvas", "illustration", "fresco"],
		categoryTerms: [],
	},
	{
		id: "sculpture",
		parents: ["art"],
		identityTerms: ["statue", "sculpture", "carving", "bust", "relief", "monument", "statuette"],
		categoryTerms: [],
	},
	{
		id: "textile",
		parents: ["art"],
		identityTerms: [
			"tapestry",
			"rug",
			"carpet",
			"embroidery",
			"mosaic",
			"wall hanging",
			"mat",
			"doormat",
			"door mat",
		],
		categoryTerms: ["textile"],
	},
	{
		id: "regalia",
		parents: ["wearable"],
		identityTerms: ["crown", "tiara", "diadem", "regalia", "royal seal", "coronet", "scepter"],
		categoryTerms: [],
		descriptorTerms: ["royal"],
	},
	{
		id: "shrine-and-altar",
		parents: [],
		identityTerms: [
			"shrine",
			"altar",
			"sanctuary",
			"reliquary",
			"memorial",
			"offering place",
			"relic",
			"idol",
			"effigy",
			"fetish",
			"totem",
			"censer",
			"chalice",
			"goblet",
			"offering",
		],
		categoryTerms: ["cult object", "ritual", "ceremonial"],
		descriptorTerms: ["sacred", "holy", "devotional", "consecrated"],
	},
	{
		id: "egg-and-nest",
		parents: ["food", "fauna"],
		identityTerms: ["egg", "eggs", "nest", "bird nest", "hatchling", "shell", "eggshell"],
		categoryTerms: [],
	},
	{
		id: "bell-and-chime",
		parents: ["music"],
		identityTerms: ["bell", "chime", "handbell", "school bell", "sleigh bell", "alarm bell"],
		categoryTerms: [],
	},
	{
		id: "treasure",
		parents: [],
		identityTerms: [
			"treasure",
			"loot",
			"bounty",
			"gem",
			"jewel",
			"gemstone",
			"crystal",
			"diamond",
			"ruby",
			"emerald",
		],
		categoryTerms: [],
		descriptorTerms: ["valuable", "wealth", "precious"],
	},
	{
		id: "coin",
		parents: ["treasure"],
		identityTerms: ["coin", "currency", "money", "medallion"],
		categoryTerms: ["gold", "silver", "cash"],
	},
	{
		id: "flag-and-sign",
		parents: [],
		identityTerms: [
			"flag",
			"banner",
			"pennant",
			"standard",
			"sign",
			"signpost",
			"marker",
			"trail marker",
		],
		categoryTerms: [],
	},
	{
		id: "jewelry",
		parents: ["treasure"],
		identityTerms: ["jewelry", "jewellery", "ring", "necklace", "amulet", "bracelet", "brooch"],
		categoryTerms: [],
	},
	{
		id: "music",
		parents: [],
		identityTerms: ["music", "musical", "instrument", "sound", "melody", "noisemaker"],
		categoryTerms: [],
	},
	{
		id: "string-instrument",
		parents: ["music"],
		identityTerms: ["lute", "harp", "lyre", "violin", "fiddle", "guitar", "strings"],
		categoryTerms: ["string instrument"],
	},
	{
		id: "wind-instrument",
		parents: ["music"],
		identityTerms: ["horn", "flute", "pipe", "whistle", "ocarina", "trumpet", "wind instrument"],
		categoryTerms: [],
	},
	{
		id: "percussion",
		parents: ["music"],
		identityTerms: ["drum", "gong", "cymbal", "rattle", "percussion"],
		categoryTerms: [],
	},
	{
		id: "magic",
		parents: [],
		identityTerms: [
			"magic",
			"arcane",
			"spell",
			"sorcery",
			"rune",
			"glyph",
			"sigil",
			"ward",
			"magic mark",
		],
		categoryTerms: [],
		descriptorTerms: ["magical", "enchanted", "supernatural"],
	},
	{
		id: "wand-and-staff",
		parents: ["magic"],
		identityTerms: ["wand", "staff", "rod", "stave", "focus", "spell focus", "magic wand"],
		categoryTerms: [],
	},
	{
		id: "potion",
		parents: ["magic"],
		identityTerms: ["potion", "elixir", "tonic", "philter", "draught", "brew", "poison"],
		categoryTerms: [],
	},
	{
		id: "orb",
		parents: ["magic"],
		identityTerms: ["orb", "sphere", "scrying", "crystal ball", "seeing stone", "magic orb"],
		categoryTerms: [],
	},
	{
		id: "thread-and-sewing",
		parents: ["tool"],
		identityTerms: [
			"thread",
			"yarn",
			"needle",
			"sewing",
			"stitching",
			"spool",
			"bobbin",
			"thimble",
			"embroidery thread",
		],
		categoryTerms: ["sewing tool"],
	},
	{
		id: "spellbook",
		parents: ["book", "magic"],
		identityTerms: [
			"spellbook",
			"spell book",
			"grimoire",
			"book of spells",
			"incantation",
			"magic tome",
			"arcane book",
		],
		categoryTerms: [],
	},
] as const;

export type ItemIconCategory = (typeof itemIconCatalog)[number]["id"];
export type ItemIconTermKind = "identity" | "category" | "descriptor";

export type ItemIconCategoryDefinition = {
	id: ItemIconCategory;
	parents: readonly ItemIconCategory[];
	identityTerms: readonly string[];
	categoryTerms: readonly string[];
	descriptorTerms?: readonly string[];
};

export const ITEM_ICON_CATALOG: readonly ItemIconCategoryDefinition[] = itemIconCatalog;

export const ITEM_ICON_CATEGORIES = itemIconCatalog.map((entry) => entry.id);

export const NON_VISUAL_ITEM_TAGS = new Set([
	"takeable",
	"openable",
	"surface",
	"drinkable",
	"rollable",
	"diggable",
	"chaseable",
	"usable",
	"scent",
	"landmark",
	"hiding place",
	"goal item",
	"goal container",
	"scenery",
]);
