import {
	AlertDiamondIcon,
	ArmchairIcon,
	ArmoredBootIcon,
	AxeIcon,
	BandageIcon,
	BarrelIcon,
	BaseballBatIcon,
	BedSingle02Icon,
	BellIcon,
	BirdIcon,
	BodyArmorIcon,
	Bone01Icon,
	BombIcon,
	Book02Icon,
	BookKeyIcon,
	Bookshelf01Icon,
	BowArrowIcon,
	BoxingGlove01Icon,
	Bread01Icon,
	BrickWallIcon,
	BridgeIcon,
	CarrotIcon,
	Castle01Icon,
	Certificate01Icon,
	Chair03Icon,
	ChinaTempleIcon,
	ClothesIcon,
	Coins01Icon,
	Compass01Icon,
	CookingPotIcon,
	Crown02Icon,
	DicesIcon,
	DiningTableIcon,
	DoorClosedIcon,
	DoorLockIcon,
	DoorOpenIcon,
	DrinkIcon,
	DrumIcon,
	EggsIcon,
	EngineIcon,
	FenceIcon,
	FilmRoll02Icon,
	FirePitIcon,
	FishingRodIcon,
	Flag01Icon,
	FlowerIcon,
	GearsIcon,
	GeometricShapes01Icon,
	GoldIngotsIcon,
	GreekHelmetIcon,
	GuitarIcon,
	GunIcon,
	HammerIcon,
	HoodieIcon,
	Image03Icon,
	KeyIcon,
	Knife02Icon,
	KnightShieldIcon,
	LanternIcon,
	Leaf01Icon,
	Link03Icon,
	MagicWand01Icon,
	MagicWand03Icon,
	MailOpen01Icon,
	MapsIcon,
	MaskTheater02Icon,
	MilkBottleIcon,
	MoneyBag01Icon,
	MushroomIcon,
	MusicNote01Icon,
	NecklaceIcon,
	OilBarrelIcon,
	OlympicTorchIcon,
	Orbit02Icon,
	PackageIcon,
	PenTool03Icon,
	PotionIcon,
	PrayerRugIcon,
	PrisonIcon,
	RiceBowl01Icon,
	SailboatOffshoreIcon,
	Shapes01Icon,
	ShovelIcon,
	SkullIcon,
	SphereIcon,
	Stairs02Icon,
	Sword01Icon,
	Sword03Icon,
	ThreadIcon,
	TicketStarIcon,
	ToggleOnIcon,
	ToyTrainIcon,
	Tree02Icon,
	User02Icon,
	VegetarianFoodIcon,
	VenetianMaskIcon,
	VintageClockIcon,
	WashingtonMonumentIcon,
	WaterPumpIcon,
	WhistleIcon,
} from "@hugeicons/core-free-icons";
import type {IconSvgElement} from "@hugeicons/react";
import type {ItemIconCategory} from "./itemIconCatalog";

export type ItemIconLibraryEntry = {
	icon: IconSvgElement;
	iconName: string;
};

export const ITEM_ICON_LIBRARY = {
	generic: {icon: Shapes01Icon, iconName: "Shapes01Icon"},
	"toy-and-game": {icon: DicesIcon, iconName: "DicesIcon"},
	vehicle: {icon: ToyTrainIcon, iconName: "ToyTrainIcon"},
	boat: {icon: SailboatOffshoreIcon, iconName: "SailboatOffshoreIcon"},
	structure: {icon: Castle01Icon, iconName: "Castle01Icon"},
	fortification: {icon: BrickWallIcon, iconName: "BrickWallIcon"},
	bridge: {icon: BridgeIcon, iconName: "BridgeIcon"},
	stairs: {icon: Stairs02Icon, iconName: "Stairs02Icon"},
	"well-and-fountain": {icon: WaterPumpIcon, iconName: "WaterPumpIcon"},
	door: {icon: DoorClosedIcon, iconName: "DoorClosedIcon"},
	gate: {icon: FenceIcon, iconName: "FenceIcon"},
	hatch: {icon: DoorOpenIcon, iconName: "DoorOpenIcon"},
	portal: {icon: Orbit02Icon, iconName: "Orbit02Icon"},
	furniture: {icon: ArmchairIcon, iconName: "ArmchairIcon"},
	seat: {icon: Chair03Icon, iconName: "Chair03Icon"},
	table: {icon: DiningTableIcon, iconName: "DiningTableIcon"},
	bed: {icon: BedSingle02Icon, iconName: "BedSingle02Icon"},
	"shelf-and-cabinet": {icon: Bookshelf01Icon, iconName: "Bookshelf01Icon"},
	container: {icon: BarrelIcon, iconName: "BarrelIcon"},
	chest: {icon: PackageIcon, iconName: "PackageIcon"},
	barrel: {icon: OilBarrelIcon, iconName: "OilBarrelIcon"},
	bag: {icon: MoneyBag01Icon, iconName: "MoneyBag01Icon"},
	bottle: {icon: MilkBottleIcon, iconName: "MilkBottleIcon"},
	cage: {icon: PrisonIcon, iconName: "PrisonIcon"},
	mechanism: {icon: GearsIcon, iconName: "GearsIcon"},
	control: {icon: ToggleOnIcon, iconName: "ToggleOnIcon"},
	clock: {icon: VintageClockIcon, iconName: "VintageClockIcon"},
	trap: {icon: AlertDiamondIcon, iconName: "AlertDiamondIcon"},
	lock: {icon: DoorLockIcon, iconName: "DoorLockIcon"},
	engine: {icon: EngineIcon, iconName: "EngineIcon"},
	tool: {icon: ShovelIcon, iconName: "ShovelIcon"},
	hammer: {icon: HammerIcon, iconName: "HammerIcon"},
	rope: {icon: ThreadIcon, iconName: "ThreadIcon"},
	"writing-tool": {icon: PenTool03Icon, iconName: "PenTool03Icon"},
	"cooking-tool": {icon: CookingPotIcon, iconName: "CookingPotIcon"},
	"medical-tool": {icon: BandageIcon, iconName: "BandageIcon"},
	"navigation-tool": {icon: Compass01Icon, iconName: "Compass01Icon"},
	key: {icon: KeyIcon, iconName: "KeyIcon"},
	credential: {icon: TicketStarIcon, iconName: "TicketStarIcon"},
	weapon: {icon: Sword03Icon, iconName: "Sword03Icon"},
	blade: {icon: Sword01Icon, iconName: "Sword01Icon"},
	axe: {icon: AxeIcon, iconName: "AxeIcon"},
	bow: {icon: BowArrowIcon, iconName: "BowArrowIcon"},
	knife: {icon: Knife02Icon, iconName: "Knife02Icon"},
	"blunt-weapon": {icon: BaseballBatIcon, iconName: "BaseballBatIcon"},
	firearm: {icon: GunIcon, iconName: "GunIcon"},
	shield: {icon: KnightShieldIcon, iconName: "KnightShieldIcon"},
	wearable: {icon: ClothesIcon, iconName: "ClothesIcon"},
	armor: {icon: BodyArmorIcon, iconName: "BodyArmorIcon"},
	headwear: {icon: GreekHelmetIcon, iconName: "GreekHelmetIcon"},
	footwear: {icon: ArmoredBootIcon, iconName: "ArmoredBootIcon"},
	gloves: {icon: BoxingGlove01Icon, iconName: "BoxingGlove01Icon"},
	cloak: {icon: HoodieIcon, iconName: "HoodieIcon"},
	mask: {icon: VenetianMaskIcon, iconName: "VenetianMaskIcon"},
	light: {icon: LanternIcon, iconName: "LanternIcon"},
	torch: {icon: OlympicTorchIcon, iconName: "OlympicTorchIcon"},
	"chain-and-link": {icon: Link03Icon, iconName: "Link03Icon"},
	fire: {icon: FirePitIcon, iconName: "FirePitIcon"},
	document: {icon: Certificate01Icon, iconName: "Certificate01Icon"},
	book: {icon: Book02Icon, iconName: "Book02Icon"},
	explosive: {icon: BombIcon, iconName: "BombIcon"},
	map: {icon: MapsIcon, iconName: "MapsIcon"},
	letter: {icon: MailOpen01Icon, iconName: "MailOpen01Icon"},
	food: {icon: VegetarianFoodIcon, iconName: "VegetarianFoodIcon"},
	produce: {icon: CarrotIcon, iconName: "CarrotIcon"},
	"bread-and-pastry": {icon: Bread01Icon, iconName: "Bread01Icon"},
	meal: {icon: RiceBowl01Icon, iconName: "RiceBowl01Icon"},
	drink: {icon: DrinkIcon, iconName: "DrinkIcon"},
	nature: {icon: Leaf01Icon, iconName: "Leaf01Icon"},
	"wood-and-tree": {icon: Tree02Icon, iconName: "Tree02Icon"},
	"herb-and-flower": {icon: FlowerIcon, iconName: "FlowerIcon"},
	fungus: {icon: MushroomIcon, iconName: "MushroomIcon"},
	"stone-and-mineral": {icon: GeometricShapes01Icon, iconName: "GeometricShapes01Icon"},
	fauna: {icon: BirdIcon, iconName: "BirdIcon"},
	remains: {icon: SkullIcon, iconName: "SkullIcon"},
	"fishing-tool": {icon: FishingRodIcon, iconName: "FishingRodIcon"},
	bone: {icon: Bone01Icon, iconName: "Bone01Icon"},
	grave: {icon: WashingtonMonumentIcon, iconName: "WashingtonMonumentIcon"},
	art: {icon: MaskTheater02Icon, iconName: "MaskTheater02Icon"},
	painting: {icon: Image03Icon, iconName: "Image03Icon"},
	sculpture: {icon: User02Icon, iconName: "User02Icon"},
	textile: {icon: PrayerRugIcon, iconName: "PrayerRugIcon"},
	regalia: {icon: Crown02Icon, iconName: "Crown02Icon"},
	"shrine-and-altar": {icon: ChinaTempleIcon, iconName: "ChinaTempleIcon"},
	"egg-and-nest": {icon: EggsIcon, iconName: "EggsIcon"},
	"bell-and-chime": {icon: BellIcon, iconName: "BellIcon"},
	treasure: {icon: GoldIngotsIcon, iconName: "GoldIngotsIcon"},
	coin: {icon: Coins01Icon, iconName: "Coins01Icon"},
	"flag-and-sign": {icon: Flag01Icon, iconName: "Flag01Icon"},
	jewelry: {icon: NecklaceIcon, iconName: "NecklaceIcon"},
	music: {icon: MusicNote01Icon, iconName: "MusicNote01Icon"},
	"string-instrument": {icon: GuitarIcon, iconName: "GuitarIcon"},
	"wind-instrument": {icon: WhistleIcon, iconName: "WhistleIcon"},
	percussion: {icon: DrumIcon, iconName: "DrumIcon"},
	magic: {icon: MagicWand01Icon, iconName: "MagicWand01Icon"},
	"wand-and-staff": {icon: MagicWand03Icon, iconName: "MagicWand03Icon"},
	potion: {icon: PotionIcon, iconName: "PotionIcon"},
	orb: {icon: SphereIcon, iconName: "SphereIcon"},
	"thread-and-sewing": {icon: FilmRoll02Icon, iconName: "FilmRoll02Icon"},
	spellbook: {icon: BookKeyIcon, iconName: "BookKeyIcon"},
} as const satisfies Record<ItemIconCategory, ItemIconLibraryEntry>;

export const OFFICIAL_ITEM_ICON_NAMES = Object.fromEntries(
	Object.entries(ITEM_ICON_LIBRARY).map(([category, entry]) => [category, entry.iconName]),
) as Readonly<Record<ItemIconCategory, string>>;
