import {
	Apple01Icon,
	ArmoredBootIcon,
	Archive01Icon,
	AxeIcon,
	BandageIcon,
	BarrelIcon,
	BedSingle01Icon,
	BodyArmorIcon,
	Bone01Icon,
	Book01Icon,
	BookLockIcon,
	BowArrowIcon,
	Bread01Icon,
	BrickWallIcon,
	BridgeIcon,
	Cabinet01Icon,
	CampfireIcon,
	CapIcon,
	CastleIcon,
	Chair01Icon,
	Chair03Icon,
	Compass01Icon,
	CookingPotIcon,
	Coins01Icon,
	ClubIcon,
	ClothesIcon,
	CrossIcon,
	Diamond01Icon,
	DiceIcon,
	DoorClosedIcon,
	DoorOpenIcon,
	DrinkIcon,
	DrumIcon,
	EngineIcon,
	FeatherIcon,
	FenceIcon,
	Fire02Icon,
	GlassWaterIcon,
	GeometricShapes01Icon,
	GolfCartIcon,
	GearsIcon,
	GemIcon,
	GloveIcon,
	GreekHelmetIcon,
	GuitarIcon,
	HammerIcon,
	Image03Icon,
	Knife01Icon,
	Key01Icon,
	KnightShieldIcon,
	LanternIcon,
	Leaf01Icon,
	Leaf02Icon,
	LockIcon,
	LongSleeveShirtIcon,
	MagicWand01Icon,
	MagicWand03Icon,
	MailOpen01Icon,
	MapsIcon,
	MaskTheaterIcon,
	MedicineBottle01Icon,
	MoneyBag01Icon,
	Mushroom01Icon,
	MusicNote01Icon,
	NaturalFoodIcon,
	NecklaceIcon,
	OlympicTorchIcon,
	PackageIcon,
	PotionIcon,
	PrayerRug01Icon,
	PrisonIcon,
	QuillWrite01Icon,
	RiceBowl01Icon,
	SafeBoxIcon,
	SailboatCoastalIcon,
	ScrollHorizontalIcon,
	ScrollVerticalIcon,
	ShovelIcon,
	SkullIcon,
	SkippingRopeIcon,
	SparklesIcon,
	SphereIcon,
	Stairs01Icon,
	Sword01Icon,
	Sword03Icon,
	Table01Icon,
	Target01Icon,
	Ticket01Icon,
	TextSquareIcon,
	ToggleOnIcon,
	Tree01Icon,
	ToyTrainIcon,
	UnavailableIcon,
	VenetianMaskIcon,
	VintageClockIcon,
	VolumeHighIcon,
	WaterPumpIcon,
	WhistleIcon,
	WorkflowCircle06Icon,
	WorkoutBattleRopesIcon,
	Orbit02Icon,
	Grid2X2Icon,
	LinkCircle02Icon,
	BaseballBatIcon,
	GunIcon,
	HoodieIcon,
	User03Icon,
	UserMinus01Icon,
	WashingtonMonumentIcon,
	Alien01Icon,
	Shapes01Icon,
	Lamp01Icon,
	ActivitySparkIcon,
	AlertDiamondIcon,
	ArmchairIcon,
	AudioWaveformIcon,
	BedDoubleIcon,
	BedSingle02Icon,
	BirdIcon,
	BloodBottleIcon,
	Bone02Icon,
	BoneIcon,
	Book02Icon,
	BookBookmark01Icon,
	BookBookmarkIcon,
	BookKeyIcon,
	Bookshelf01Icon,
	BoatIcon,
	BoxingGlove01Icon,
	Bread02Icon,
	Bread03Icon,
	BrickWallShieldIcon,
	Cabinet02Icon,
	CarrotIcon,
	Castle01Icon,
	Castle02Icon,
	Chair02Icon,
	ChinaTempleIcon,
	CircleArrowDataTransferHorizontalIcon,
	Clock01Icon,
	CodeSquareIcon,
	Coffee01Icon,
	CoinsDollarIcon,
	CompassIcon,
	DiamondIcon,
	DiningTableIcon,
	DiscoverCircleIcon,
	DicesIcon,
	Door01Icon,
	DoorLockIcon,
	DrumstickIcon,
	EarRings01Icon,
	Fire03Icon,
	FirePitIcon,
	FirstAidKitIcon,
	FlowerIcon,
	FrameIcon,
	GraduationScrollIcon,
	Grid3X3Icon,
	HandBag01Icon,
	HorseHeadIcon,
	HourglassIcon,
	Image02Icon,
	Key02Icon,
	KeyIcon,
	Leaf03Icon,
	LeafyGreenIcon,
	LegalDocument01Icon,
	Link01Icon,
	MagicWand02Icon,
	MagicWand04Icon,
	MagicWand05Icon,
	Mail01Icon,
	Mail02Icon,
	MapingIcon,
	MapsCircle01Icon,
	MaskIcon,
	MaskTheater01Icon,
	MaskTheater02Icon,
	MedicineBottle02Icon,
	MilkBottleIcon,
	MushroomIcon,
	Money03Icon,
	MoneyBag02Icon,
	MoneySafeIcon,
	MusicNote02Icon,
	MusicThreeIcon,
	OilBarrelIcon,
	Orbit01Icon,
	OrganicFoodIcon,
	PineTreeIcon,
	PrayerRug02Icon,
	PrayerRugIcon,
	QuillWrite02Icon,
	QuillWriteIcon,
	RemoteControlIcon,
	Restaurant01Icon,
	RestaurantTableIcon,
	RiceBowl02Icon,
	RunningShoesIcon,
	SailboatOffshoreIcon,
	Scroll01Icon,
	ServingFoodIcon,
	Shirt01Icon,
	Shield01Icon,
	Shield02Icon,
	SoftDrink01Icon,
	SpartanHelmetIcon,
	SpoonAndKnifeIcon,
	SquareLock02Icon,
	Stairs02Icon,
	Stairs03Icon,
	StudyLampIcon,
	Sword02Icon,
	Ticket02Icon,
	TicketStarIcon,
	ToggleOffIcon,
	TorriGateIcon,
	TelescopeIcon,
	ToyBrickIcon,
	Train01Icon,
	Tree02Icon,
	User02Icon,
	VegetarianFoodIcon,
	WaterfallDownIcon,
	Certificate01Icon,
	ChartCandlestickIcon,
	ContractsIcon,
	Crown03Icon,
	CrownIcon,
	DeadIcon,
	File01Icon,
	FlameKindlingIcon,
	GoldIngotsIcon,
	Knife02Icon,
	LampWallUpIcon,
	LicenseIcon,
	BellIcon,
	BombIcon,
	ConciergeBellIcon,
	Crown02Icon,
	EggFriedIcon,
	EggIcon,
	EggsIcon,
	FishFoodIcon,
	FishingHookIcon,
	FishingRodIcon,
	Flag01Icon,
	Flag02Icon,
	Flag03Icon,
	FireworksIcon,
	FilmRoll02Icon,
	KnifeIcon,
	Link02Icon,
	Link03Icon,
	PenTool03Icon,
	PocketKnifeIcon,
	SchoolBell01Icon,
	ThreadIcon,
	ThreadsIcon,
	ThreadsRectangleIcon,
} from "@hugeicons/core-free-icons";
import type {IconSvgElement} from "@hugeicons/react";

export type HugeIconFit = "Exact" | "Close";

export type HugeIconMatch = {
	fit: HugeIconFit;
	icon: IconSvgElement;
	iconName: string;
	note: string;
};

const exact = (icon: IconSvgElement, iconName: string, note: string): HugeIconMatch => ({
	fit: "Exact",
	icon,
	iconName,
	note,
});

const close = (icon: IconSvgElement, iconName: string, note: string): HugeIconMatch => ({
	fit: "Close",
	icon,
	iconName,
	note,
});

/**
 * Deliberately conservative Hugeicons audit of the 100-mark item icon specification. A close match
 * must still identify a term explicitly covered by the category; merely sharing a vague outline is
 * not enough. Omitted categories render the shared crossed-out mark in the review gallery.
 */
export const HUGE_ICON_MATCHES: Readonly<Record<string, HugeIconMatch>> = {
	generic: exact(
		SparklesIcon,
		"SparklesIcon",
		"A restrained fallback for an unknown curious object.",
	),
	"toy-and-game": exact(DiceIcon, "DiceIcon", "A die is one of the category's canonical subjects."),
	boat: exact(SailboatCoastalIcon, "SailboatCoastalIcon", "A compact sailboat silhouette."),
	structure: exact(
		CastleIcon,
		"CastleIcon",
		"A fantasy structure with a strong architectural silhouette.",
	),
	fortification: exact(BrickWallIcon, "BrickWallIcon", "A short masonry wall."),
	bridge: exact(BridgeIcon, "BridgeIcon", "A clear arched bridge."),
	stairs: exact(Stairs01Icon, "Stairs01Icon", "Three ascending steps."),
	"well-and-fountain": close(
		WaterPumpIcon,
		"WaterPumpIcon",
		"Water pump is an explicit identity term, though the spec prefers a roofed well.",
	),
	door: exact(DoorClosedIcon, "DoorClosedIcon", "A closed physical door with an unambiguous frame."),
	gate: close(
		FenceIcon,
		"FenceIcon",
		"Fits fence and railing aliases, but is less specific than a portcullis.",
	),
	furniture: exact(Chair01Icon, "Chair01Icon", "A high-backed furniture silhouette."),
	seat: exact(Chair03Icon, "Chair03Icon", "A distinct, sturdy chair."),
	table: exact(Table01Icon, "Table01Icon", "A plain table shown in stable perspective."),
	bed: exact(BedSingle01Icon, "BedSingle01Icon", "A side-view single bed with pillow."),
	"shelf-and-cabinet": exact(
		Cabinet01Icon,
		"Cabinet01Icon",
		"A narrow cabinet with visible divisions.",
	),
	container: close(
		PackageIcon,
		"PackageIcon",
		"A generic physical container rather than the preferred bound chest.",
	),
	chest: close(SafeBoxIcon, "SafeBoxIcon", "A sturdy lockbox that reads as secure storage."),
	barrel: exact(BarrelIcon, "BarrelIcon", "An upright barrel with consistent hoops."),
	bag: exact(MoneyBag01Icon, "MoneyBag01Icon", "A tied drawstring pouch with a coherent opening."),
	bottle: exact(
		MedicineBottle01Icon,
		"MedicineBottle01Icon",
		"A stoppered bottle with a readable body and neck.",
	),
	mechanism: exact(GearsIcon, "GearsIcon", "Interlocking gears with clear mechanical meaning."),
	control: close(
		ToggleOnIcon,
		"ToggleOnIcon",
		"A switch is an explicit control term, though this treatment is contemporary.",
	),
	clock: exact(VintageClockIcon, "VintageClockIcon", "A readable mechanical clock face."),
	lock: exact(LockIcon, "LockIcon", "A conventional padlock."),
	engine: exact(EngineIcon, "EngineIcon", "A compact engine silhouette."),
	tool: close(
		ShovelIcon,
		"ShovelIcon",
		"Shovel is an explicit tool term; the preferred canonical subject remains a pickaxe.",
	),
	hammer: exact(HammerIcon, "HammerIcon", "A recognizable hand hammer."),
	"writing-tool": exact(
		QuillWrite01Icon,
		"QuillWrite01Icon",
		"A quill and ink line suited to the fantasy vocabulary.",
	),
	"cooking-tool": exact(CookingPotIcon, "CookingPotIcon", "A handled cooking pot."),
	"medical-tool": exact(BandageIcon, "BandageIcon", "A clear rolled bandage."),
	"navigation-tool": exact(
		Compass01Icon,
		"Compass01Icon",
		"A pocket compass with four clear points.",
	),
	key: exact(Key01Icon, "Key01Icon", "An old-fashioned key silhouette."),
	credential: exact(Ticket01Icon, "Ticket01Icon", "A clipped ticket or pass."),
	weapon: exact(Sword03Icon, "Sword03Icon", "Crossed swords communicate the broad weapon category."),
	blade: exact(Sword01Icon, "Sword01Icon", "One sword with a readable crossguard."),
	axe: exact(AxeIcon, "AxeIcon", "A single broad-headed axe."),
	bow: exact(BowArrowIcon, "BowArrowIcon", "A curved bow with arrow."),
	shield: exact(KnightShieldIcon, "KnightShieldIcon", "A restrained fantasy shield."),
	armor: exact(BodyArmorIcon, "BodyArmorIcon", "A simple breastplate."),
	headwear: exact(GreekHelmetIcon, "GreekHelmetIcon", "An open-faced historical helmet."),
	footwear: exact(ArmoredBootIcon, "ArmoredBootIcon", "A fantasy-appropriate armored boot."),
	gloves: exact(GloveIcon, "GloveIcon", "One articulated glove."),
	mask: exact(VenetianMaskIcon, "VenetianMaskIcon", "An asymmetrical masquerade mask."),
	light: exact(LanternIcon, "LanternIcon", "A handled lantern."),
	torch: close(
		OlympicTorchIcon,
		"OlympicTorchIcon",
		"A hand-held torch with a compact flame; the cup is more formal than rustic.",
	),
	fire: exact(CampfireIcon, "CampfireIcon", "Logs beneath a restrained flame."),
	document: exact(ScrollVerticalIcon, "ScrollVerticalIcon", "A vertical parchment-like document."),
	book: exact(Book01Icon, "Book01Icon", "A closed book with spine and page block."),
	scroll: exact(
		ScrollHorizontalIcon,
		"ScrollHorizontalIcon",
		"A horizontal scroll with both ends rolled.",
	),
	map: exact(MapsIcon, "MapsIcon", "A folded map silhouette."),
	letter: exact(
		MailOpen01Icon,
		"MailOpen01Icon",
		"An open envelope that clearly communicates correspondence.",
	),
	food: exact(NaturalFoodIcon, "NaturalFoodIcon", "A grouped natural-food composition."),
	produce: close(
		Apple01Icon,
		"Apple01Icon",
		"A strong produce identity, though it omits the supporting carrot.",
	),
	"bread-and-pastry": exact(Bread01Icon, "Bread01Icon", "A scored loaf."),
	meal: exact(RiceBowl01Icon, "RiceBowl01Icon", "A prepared bowl meal with utensil."),
	drink: exact(DrinkIcon, "DrinkIcon", "A handled beverage vessel with a liquid cue."),
	nature: exact(
		Leaf01Icon,
		"Leaf01Icon",
		"The visual benchmark: a quiet leaf silhouette with restrained interior detail.",
	),
	"wood-and-tree": close(
		Tree01Icon,
		"Tree01Icon",
		"A tree rather than the preferred cut branch, but it directly matches the category.",
	),
	"herb-and-flower": exact(Leaf02Icon, "Leaf02Icon", "A small botanical sprig."),
	fungus: exact(Mushroom01Icon, "Mushroom01Icon", "A compact mushroom group."),
	fauna: close(
		FeatherIcon,
		"FeatherIcon",
		"A feather is part of the canonical fauna subject and remains broadly readable.",
	),
	remains: exact(SkullIcon, "SkullIcon", "A clear skull silhouette."),
	bone: exact(Bone01Icon, "Bone01Icon", "One clean rounded bone."),
	art: exact(
		MaskTheaterIcon,
		"MaskTheaterIcon",
		"Paired theatrical masks for the broad art category.",
	),
	painting: close(
		Image03Icon,
		"Image03Icon",
		"A framed landscape image without medium-specific decoration.",
	),
	textile: close(
		PrayerRug01Icon,
		"PrayerRug01Icon",
		"A hanging or floor textile with a distinct edge treatment.",
	),
	treasure: exact(GemIcon, "GemIcon", "A faceted valuable object."),
	coin: exact(Coins01Icon, "Coins01Icon", "A small overlapping coin stack."),
	gem: exact(Diamond01Icon, "Diamond01Icon", "A single cut gemstone."),
	jewelry: exact(NecklaceIcon, "NecklaceIcon", "A recognizable piece of jewelry."),
	music: exact(MusicNote01Icon, "MusicNote01Icon", "A broad, immediately readable music symbol."),
	"string-instrument": close(
		GuitarIcon,
		"GuitarIcon",
		"A string instrument, though the spec prefers a fantasy-leaning lyre.",
	),
	percussion: exact(DrumIcon, "DrumIcon", "A compact hand drum."),
	magic: exact(MagicWand01Icon, "MagicWand01Icon", "A restrained magical focus and spark."),
	"wand-and-staff": exact(
		MagicWand03Icon,
		"MagicWand03Icon",
		"A short wand with a clear magical cue.",
	),
	potion: exact(PotionIcon, "PotionIcon", "A stoppered potion vessel with contained liquid."),
	orb: exact(SphereIcon, "SphereIcon", "A dimensional sphere that reads cleanly at small sizes."),
	knife: exact(
		Knife02Icon,
		"Knife02Icon",
		"A distinct cleaver-like knife for knife and dagger terms.",
	),
	"chain-and-link": exact(
		Link01Icon,
		"Link01Icon",
		"A linked metal form distinct from coiled rope.",
	),
	explosive: exact(BombIcon, "BombIcon", "A compact, unmistakable explosive silhouette."),
	"fishing-tool": exact(
		FishingRodIcon,
		"FishingRodIcon",
		"A fishing rod and line for angling gear.",
	),
	regalia: exact(CrownIcon, "CrownIcon", "A clear crown for royal and ceremonial regalia."),
	"egg-and-nest": exact(
		EggIcon,
		"EggIcon",
		"A simple egg silhouette for eggs, nests, and hatchlings.",
	),
	"bell-and-chime": exact(BellIcon, "BellIcon", "A distinct hanging bell for bells and chimes."),
	"flag-and-sign": exact(
		Flag01Icon,
		"Flag01Icon",
		"A planted flag for markers, signs, and standards.",
	),
	"thread-and-sewing": exact(
		ThreadIcon,
		"ThreadIcon",
		"A thread mark for sewing materials and tools.",
	),
	spellbook: close(
		BookLockIcon,
		"BookLockIcon",
		"A clasped, protected book suitable for a grimoire.",
	),
};

export type HugeIconSuggestion = {
	icon: IconSvgElement;
	iconName: string;
	rationale: string;
};

export const FOLDED_CATEGORY_VOCABULARY: Readonly<Record<string, readonly string[]>> = {
	weapon: ["polearm"],
	light: ["candle"],
	document: ["scroll"],
	remains: ["corpse"],
	"shrine-and-altar": ["relic", "idol", "ritual implement"],
	treasure: ["gem"],
	magic: ["rune"],
};

const suggestion = (
	icon: IconSvgElement,
	iconName: string,
	rationale: string,
): HugeIconSuggestion => ({icon, iconName, rationale});

const alternative = (icon: IconSvgElement, iconName: string) =>
	suggestion(icon, iconName, "Alternate library treatment for this category.");

/** Two additional actual library choices for every category with an approved primary match. */
export const HUGE_ICON_ALTERNATIVES: Readonly<Record<string, readonly HugeIconSuggestion[]>> = {
	generic: [
		alternative(Shapes01Icon, "Shapes01Icon"),
		alternative(ActivitySparkIcon, "ActivitySparkIcon"),
		alternative(DiscoverCircleIcon, "DiscoverCircleIcon"),
	],
	"toy-and-game": [alternative(DicesIcon, "DicesIcon"), alternative(ToyBrickIcon, "ToyBrickIcon")],
	boat: [
		alternative(BoatIcon, "BoatIcon"),
		alternative(SailboatOffshoreIcon, "SailboatOffshoreIcon"),
	],
	structure: [alternative(Castle01Icon, "Castle01Icon"), alternative(Castle02Icon, "Castle02Icon")],
	fortification: [
		alternative(BrickWallShieldIcon, "BrickWallShieldIcon"),
		alternative(FenceIcon, "FenceIcon"),
	],
	bridge: [alternative(BrickWallIcon, "BrickWallIcon"), alternative(Stairs01Icon, "Stairs01Icon")],
	stairs: [alternative(Stairs02Icon, "Stairs02Icon"), alternative(Stairs03Icon, "Stairs03Icon")],
	"well-and-fountain": [
		alternative(WaterfallDownIcon, "WaterfallDownIcon"),
		alternative(GlassWaterIcon, "GlassWaterIcon"),
	],
	door: [alternative(Door01Icon, "Door01Icon"), alternative(DoorOpenIcon, "DoorOpenIcon")],
	gate: [alternative(TorriGateIcon, "TorriGateIcon"), alternative(DoorOpenIcon, "DoorOpenIcon")],
	furniture: [
		alternative(ArmchairIcon, "ArmchairIcon"),
		alternative(Cabinet01Icon, "Cabinet01Icon"),
	],
	seat: [alternative(Chair02Icon, "Chair02Icon"), alternative(ArmchairIcon, "ArmchairIcon")],
	table: [
		alternative(DiningTableIcon, "DiningTableIcon"),
		alternative(RestaurantTableIcon, "RestaurantTableIcon"),
	],
	bed: [
		alternative(BedSingle02Icon, "BedSingle02Icon"),
		alternative(BedDoubleIcon, "BedDoubleIcon"),
	],
	"shelf-and-cabinet": [
		alternative(Cabinet02Icon, "Cabinet02Icon"),
		alternative(Bookshelf01Icon, "Bookshelf01Icon"),
	],
	container: [alternative(SafeBoxIcon, "SafeBoxIcon"), alternative(BarrelIcon, "BarrelIcon")],
	chest: [alternative(MoneySafeIcon, "MoneySafeIcon"), alternative(PackageIcon, "PackageIcon")],
	barrel: [
		alternative(OilBarrelIcon, "OilBarrelIcon"),
		alternative(CookingPotIcon, "CookingPotIcon"),
	],
	bag: [alternative(MoneyBag02Icon, "MoneyBag02Icon"), alternative(HandBag01Icon, "HandBag01Icon")],
	bottle: [
		alternative(MedicineBottle02Icon, "MedicineBottle02Icon"),
		alternative(MilkBottleIcon, "MilkBottleIcon"),
	],
	mechanism: [alternative(EngineIcon, "EngineIcon"), alternative(ToggleOnIcon, "ToggleOnIcon")],
	control: [
		alternative(ToggleOffIcon, "ToggleOffIcon"),
		alternative(RemoteControlIcon, "RemoteControlIcon"),
	],
	clock: [alternative(Clock01Icon, "Clock01Icon"), alternative(HourglassIcon, "HourglassIcon")],
	lock: [
		alternative(SquareLock02Icon, "SquareLock02Icon"),
		alternative(DoorLockIcon, "DoorLockIcon"),
	],
	engine: [alternative(GearsIcon, "GearsIcon"), alternative(RemoteControlIcon, "RemoteControlIcon")],
	tool: [alternative(HammerIcon, "HammerIcon"), alternative(AxeIcon, "AxeIcon")],
	hammer: [alternative(AxeIcon, "AxeIcon"), alternative(ShovelIcon, "ShovelIcon")],
	"writing-tool": [
		alternative(PenTool03Icon, "PenTool03Icon"),
		alternative(QuillWrite02Icon, "QuillWrite02Icon"),
		alternative(QuillWriteIcon, "QuillWriteIcon"),
	],
	"cooking-tool": [
		alternative(Restaurant01Icon, "Restaurant01Icon"),
		alternative(SpoonAndKnifeIcon, "SpoonAndKnifeIcon"),
	],
	"medical-tool": [
		alternative(FirstAidKitIcon, "FirstAidKitIcon"),
		alternative(MedicineBottle01Icon, "MedicineBottle01Icon"),
	],
	"navigation-tool": [
		alternative(CompassIcon, "CompassIcon"),
		alternative(TelescopeIcon, "TelescopeIcon"),
	],
	key: [alternative(Key02Icon, "Key02Icon"), alternative(KeyIcon, "KeyIcon")],
	credential: [
		alternative(Ticket02Icon, "Ticket02Icon"),
		alternative(TicketStarIcon, "TicketStarIcon"),
	],
	weapon: [
		alternative(Sword02Icon, "Sword02Icon"),
		alternative(KnightShieldIcon, "KnightShieldIcon"),
	],
	blade: [alternative(Sword02Icon, "Sword02Icon"), alternative(Sword03Icon, "Sword03Icon")],
	axe: [alternative(Knife01Icon, "Knife01Icon"), alternative(ClubIcon, "ClubIcon")],
	bow: [alternative(Sword01Icon, "Sword01Icon"), alternative(KnightShieldIcon, "KnightShieldIcon")],
	shield: [alternative(Shield01Icon, "Shield01Icon"), alternative(Shield02Icon, "Shield02Icon")],
	armor: [
		alternative(GreekHelmetIcon, "GreekHelmetIcon"),
		alternative(ArmoredBootIcon, "ArmoredBootIcon"),
	],
	headwear: [alternative(SpartanHelmetIcon, "SpartanHelmetIcon"), alternative(CapIcon, "CapIcon")],
	footwear: [
		alternative(RunningShoesIcon, "RunningShoesIcon"),
		alternative(GreekHelmetIcon, "GreekHelmetIcon"),
	],
	gloves: [
		alternative(BoxingGlove01Icon, "BoxingGlove01Icon"),
		alternative(BodyArmorIcon, "BodyArmorIcon"),
	],
	mask: [alternative(MaskIcon, "MaskIcon"), alternative(MaskTheater01Icon, "MaskTheater01Icon")],
	light: [
		alternative(Lamp01Icon, "Lamp01Icon"),
		alternative(StudyLampIcon, "StudyLampIcon"),
		alternative(FlameKindlingIcon, "FlameKindlingIcon"),
		alternative(LampWallUpIcon, "LampWallUpIcon"),
		alternative(ChartCandlestickIcon, "ChartCandlestickIcon"),
	],
	torch: [alternative(Fire02Icon, "Fire02Icon"), alternative(LanternIcon, "LanternIcon")],
	fire: [alternative(FirePitIcon, "FirePitIcon"), alternative(Fire03Icon, "Fire03Icon")],
	document: [
		alternative(LegalDocument01Icon, "LegalDocument01Icon"),
		alternative(Scroll01Icon, "Scroll01Icon"),
		alternative(ContractsIcon, "ContractsIcon"),
		alternative(Certificate01Icon, "Certificate01Icon"),
		alternative(LicenseIcon, "LicenseIcon"),
		alternative(File01Icon, "File01Icon"),
	],
	book: [
		alternative(Book02Icon, "Book02Icon"),
		alternative(BookBookmark01Icon, "BookBookmark01Icon"),
	],
	scroll: [
		alternative(Scroll01Icon, "Scroll01Icon"),
		alternative(GraduationScrollIcon, "GraduationScrollIcon"),
	],
	map: [alternative(MapingIcon, "MapingIcon"), alternative(MapsCircle01Icon, "MapsCircle01Icon")],
	letter: [alternative(Mail01Icon, "Mail01Icon"), alternative(Mail02Icon, "Mail02Icon")],
	food: [
		alternative(OrganicFoodIcon, "OrganicFoodIcon"),
		alternative(VegetarianFoodIcon, "VegetarianFoodIcon"),
	],
	produce: [alternative(CarrotIcon, "CarrotIcon"), alternative(NaturalFoodIcon, "NaturalFoodIcon")],
	"bread-and-pastry": [
		alternative(Bread02Icon, "Bread02Icon"),
		alternative(Bread03Icon, "Bread03Icon"),
	],
	meal: [
		alternative(RiceBowl02Icon, "RiceBowl02Icon"),
		alternative(ServingFoodIcon, "ServingFoodIcon"),
	],
	drink: [
		alternative(SoftDrink01Icon, "SoftDrink01Icon"),
		alternative(Coffee01Icon, "Coffee01Icon"),
	],
	nature: [alternative(Leaf02Icon, "Leaf02Icon"), alternative(Leaf03Icon, "Leaf03Icon")],
	"wood-and-tree": [
		alternative(Tree02Icon, "Tree02Icon"),
		alternative(PineTreeIcon, "PineTreeIcon"),
	],
	"herb-and-flower": [
		alternative(FlowerIcon, "FlowerIcon"),
		alternative(LeafyGreenIcon, "LeafyGreenIcon"),
	],
	fungus: [alternative(MushroomIcon, "MushroomIcon"), alternative(Leaf02Icon, "Leaf02Icon")],
	fauna: [alternative(BirdIcon, "BirdIcon"), alternative(HorseHeadIcon, "HorseHeadIcon")],
	remains: [
		alternative(Bone01Icon, "Bone01Icon"),
		alternative(Bone02Icon, "Bone02Icon"),
		alternative(DeadIcon, "DeadIcon"),
		alternative(UserMinus01Icon, "UserMinus01Icon"),
	],
	bone: [alternative(Bone02Icon, "Bone02Icon"), alternative(BoneIcon, "BoneIcon")],
	art: [
		alternative(MaskTheater01Icon, "MaskTheater01Icon"),
		alternative(MaskTheater02Icon, "MaskTheater02Icon"),
	],
	painting: [alternative(FrameIcon, "FrameIcon"), alternative(Image02Icon, "Image02Icon")],
	textile: [
		alternative(PrayerRug02Icon, "PrayerRug02Icon"),
		alternative(PrayerRugIcon, "PrayerRugIcon"),
	],
	treasure: [
		alternative(DiamondIcon, "DiamondIcon"),
		alternative(Coins01Icon, "Coins01Icon"),
		alternative(GoldIngotsIcon, "GoldIngotsIcon"),
		alternative(CrownIcon, "CrownIcon"),
	],
	coin: [alternative(CoinsDollarIcon, "CoinsDollarIcon"), alternative(Money03Icon, "Money03Icon")],
	gem: [alternative(DiamondIcon, "DiamondIcon"), alternative(GemIcon, "GemIcon")],
	jewelry: [
		alternative(EarRings01Icon, "EarRings01Icon"),
		alternative(Diamond01Icon, "Diamond01Icon"),
	],
	music: [
		alternative(MusicNote02Icon, "MusicNote02Icon"),
		alternative(MusicThreeIcon, "MusicThreeIcon"),
	],
	"string-instrument": [
		alternative(MusicNote01Icon, "MusicNote01Icon"),
		alternative(AudioWaveformIcon, "AudioWaveformIcon"),
	],
	percussion: [
		alternative(DrumstickIcon, "DrumstickIcon"),
		alternative(MusicNote01Icon, "MusicNote01Icon"),
	],
	magic: [
		alternative(MagicWand02Icon, "MagicWand02Icon"),
		alternative(SparklesIcon, "SparklesIcon"),
		alternative(Shapes01Icon, "Shapes01Icon"),
		alternative(CodeSquareIcon, "CodeSquareIcon"),
	],
	"wand-and-staff": [
		alternative(MagicWand04Icon, "MagicWand04Icon"),
		alternative(MagicWand05Icon, "MagicWand05Icon"),
	],
	potion: [
		alternative(MedicineBottle01Icon, "MedicineBottle01Icon"),
		alternative(BloodBottleIcon, "BloodBottleIcon"),
	],
	orb: [alternative(Orbit01Icon, "Orbit01Icon"), alternative(Orbit02Icon, "Orbit02Icon")],
	knife: [
		alternative(Knife01Icon, "Knife01Icon"),
		alternative(PocketKnifeIcon, "PocketKnifeIcon"),
		alternative(KnifeIcon, "KnifeIcon"),
	],
	"chain-and-link": [alternative(Link02Icon, "Link02Icon"), alternative(Link03Icon, "Link03Icon")],
	explosive: [
		alternative(FireworksIcon, "FireworksIcon"),
		alternative(AlertDiamondIcon, "AlertDiamondIcon"),
	],
	"fishing-tool": [
		alternative(FishingHookIcon, "FishingHookIcon"),
		alternative(FishFoodIcon, "FishFoodIcon"),
	],
	regalia: [alternative(Crown02Icon, "Crown02Icon"), alternative(Crown03Icon, "Crown03Icon")],
	"egg-and-nest": [alternative(EggsIcon, "EggsIcon"), alternative(EggFriedIcon, "EggFriedIcon")],
	"bell-and-chime": [
		alternative(SchoolBell01Icon, "SchoolBell01Icon"),
		alternative(ConciergeBellIcon, "ConciergeBellIcon"),
	],
	"flag-and-sign": [alternative(Flag02Icon, "Flag02Icon"), alternative(Flag03Icon, "Flag03Icon")],
	"thread-and-sewing": [
		alternative(FilmRoll02Icon, "FilmRoll02Icon"),
		alternative(ThreadsIcon, "ThreadsIcon"),
		alternative(ThreadsRectangleIcon, "ThreadsRectangleIcon"),
	],
	spellbook: [
		alternative(BookKeyIcon, "BookKeyIcon"),
		alternative(BookBookmarkIcon, "BookBookmarkIcon"),
	],
};

/** Actual library icons worth auditioning for categories without an approvable direct match. */
export const HUGE_ICON_SUGGESTIONS: Readonly<Record<string, readonly HugeIconSuggestion[]>> = {
	vehicle: [
		suggestion(
			GolfCartIcon,
			"GolfCartIcon",
			"Preserves a compact wheeled profile, but reads as modern.",
		),
		suggestion(
			ToyTrainIcon,
			"ToyTrainIcon",
			"Feels playful and object-like, but narrows the broad vehicle category.",
		),
		suggestion(Train01Icon, "Train01Icon", "A third wheeled vehicle option with a strong profile."),
	],
	hatch: [
		suggestion(
			DoorOpenIcon,
			"DoorOpenIcon",
			"Communicates an opening, though it is vertical rather than floor-mounted.",
		),
		suggestion(
			Grid2X2Icon,
			"Grid2X2Icon",
			"Can read as a grate at small sizes, but lacks hinge and depth.",
		),
		suggestion(Grid3X3Icon, "Grid3X3Icon", "A denser grate treatment without physical hinges."),
	],
	portal: [
		suggestion(Orbit02Icon, "Orbit02Icon", "Suggests magical motion around an open center."),
		suggestion(
			WorkflowCircle06Icon,
			"WorkflowCircle06Icon",
			"Has a circular passage rhythm, but is more abstract.",
		),
		suggestion(
			CircleArrowDataTransferHorizontalIcon,
			"CircleArrowDataTransferHorizontalIcon",
			"A circular transfer symbol that suggests passage.",
		),
	],
	cage: [
		suggestion(
			PrisonIcon,
			"PrisonIcon",
			"Provides readable bars and confinement, but depicts a building.",
		),
		suggestion(FenceIcon, "FenceIcon", "Provides the bar language without a complete enclosure."),
		suggestion(Grid3X3Icon, "Grid3X3Icon", "A compact barred field that lacks an enclosing frame."),
	],
	trap: [
		suggestion(
			Target01Icon,
			"Target01Icon",
			"Conveys danger and triggering, but not a physical trap.",
		),
		suggestion(LinkCircle02Icon, "LinkCircle02Icon", "Hints at a snare loop, but remains abstract."),
		suggestion(
			AlertDiamondIcon,
			"AlertDiamondIcon",
			"Signals danger without depicting a physical mechanism.",
		),
	],
	rope: [
		suggestion(ThreadIcon, "ThreadIcon", "A compact spool-like treatment for rope and cord."),
		suggestion(
			SkippingRopeIcon,
			"SkippingRopeIcon",
			"Has a clear cord path, but includes modern handles.",
		),
		suggestion(
			WorkoutBattleRopesIcon,
			"WorkoutBattleRopesIcon",
			"Shows substantial rope strands, but not a tidy coil.",
		),
		suggestion(Link01Icon, "Link01Icon", "A looped-link treatment that suggests cord or chain."),
	],
	polearm: [
		suggestion(
			Knife01Icon,
			"Knife01Icon",
			"Offers the correct pointed blade language without the long shaft.",
		),
		suggestion(
			Sword01Icon,
			"Sword01Icon",
			"Keeps a fantasy weapon silhouette, but reads clearly as a sword.",
		),
		suggestion(AxeIcon, "AxeIcon", "A long-handled fantasy weapon with the wrong head shape."),
	],
	"blunt-weapon": [
		suggestion(
			ClubIcon,
			"ClubIcon",
			"Directly matches the club alias, but not the requested morning star.",
		),
		suggestion(
			BaseballBatIcon,
			"BaseballBatIcon",
			"Has the correct blunt profile, but is too contemporary.",
		),
		suggestion(
			HammerIcon,
			"HammerIcon",
			"A physically coherent blunt tool that lacks the morning-star head.",
		),
	],
	firearm: [
		suggestion(GunIcon, "GunIcon", "Directly communicates firearm, but is not a fantasy flintlock."),
		suggestion(
			Target01Icon,
			"Target01Icon",
			"Communicates ranged attack without depicting the weapon.",
		),
		suggestion(
			Knife01Icon,
			"Knife01Icon",
			"Retains a compact weapon silhouette but is not a firearm.",
		),
	],
	wearable: [
		suggestion(CapIcon, "CapIcon", "A clear wearable silhouette, but contemporary."),
		suggestion(
			ClothesIcon,
			"ClothesIcon",
			"Communicates the broad apparel category without one dominant fantasy object.",
		),
		suggestion(Shirt01Icon, "Shirt01Icon", "A third broad apparel silhouette."),
	],
	cloak: [
		suggestion(
			HoodieIcon,
			"HoodieIcon",
			"Retains a hooded garment silhouette, but reads as modern clothing.",
		),
		suggestion(
			LongSleeveShirtIcon,
			"LongSleeveShirtIcon",
			"Reads as a hanging garment, but lacks drape and clasp.",
		),
		suggestion(ClothesIcon, "ClothesIcon", "A broad garment fallback without cloak-specific drape."),
	],
	candle: [
		suggestion(Lamp01Icon, "Lamp01Icon", "Preserves the small-light meaning, but is not wax-based."),
		suggestion(
			Fire02Icon,
			"Fire02Icon",
			"Supplies the flame silhouette without the physical candle body.",
		),
		suggestion(LanternIcon, "LanternIcon", "A contained flame and vessel, but not a candle."),
	],
	"stone-and-mineral": [
		suggestion(
			GemIcon,
			"GemIcon",
			"Has useful facets, but reads as precious treasure rather than common rock.",
		),
		suggestion(
			GeometricShapes01Icon,
			"GeometricShapes01Icon",
			"Can suggest a rock cluster, but remains abstract geometry.",
		),
		suggestion(
			DiamondIcon,
			"DiamondIcon",
			"A faceted mineral silhouette that reads as too precious.",
		),
	],
	corpse: [
		suggestion(
			UserMinus01Icon,
			"UserMinus01Icon",
			"Suggests an absent person, but not a physical body.",
		),
		suggestion(
			BedSingle01Icon,
			"BedSingle01Icon",
			"Provides a recumbent composition, but no figure or shroud.",
		),
		suggestion(
			SkullIcon,
			"SkullIcon",
			"Communicates death directly but not the wrapped body subject.",
		),
	],
	grave: [
		suggestion(
			Archive01Icon,
			"Archive01Icon",
			"Its lidded stone-like form can hint at a sarcophagus.",
		),
		suggestion(
			CrossIcon,
			"CrossIcon",
			"Can identify a grave in some settings, but is culturally specific.",
		),
		suggestion(
			WashingtonMonumentIcon,
			"WashingtonMonumentIcon",
			"A standing memorial form that is too culturally specific.",
		),
	],
	sculpture: [
		suggestion(
			User03Icon,
			"User03Icon",
			"Supplies a centered human bust silhouette without a plinth.",
		),
		suggestion(
			WashingtonMonumentIcon,
			"WashingtonMonumentIcon",
			"Communicates monument, but is too specific and architectural.",
		),
		suggestion(
			User02Icon,
			"User02Icon",
			"A second human figure treatment without material or plinth cues.",
		),
	],
	relic: [
		suggestion(CrossIcon, "CrossIcon", "Communicates a sacred object, but is culturally specific."),
		suggestion(
			ChinaTempleIcon,
			"ChinaTempleIcon",
			"Feels sacred and historical, but depicts architecture rather than an object.",
		),
		suggestion(GemIcon, "GemIcon", "Reads as a precious cult object, but not a reliquary."),
	],
	"shrine-and-altar": [
		suggestion(
			ChinaTempleIcon,
			"ChinaTempleIcon",
			"Reads as a shrine, though it is a full structure.",
		),
		suggestion(Table01Icon, "Table01Icon", "Provides the physical altar form without sacred cues."),
		suggestion(
			PrayerRug01Icon,
			"PrayerRug01Icon",
			"Adds devotional context but changes the physical object.",
		),
	],
	idol: [
		suggestion(
			Alien01Icon,
			"Alien01Icon",
			"Has a compact carved-figure silhouette, but the face is too literal.",
		),
		suggestion(
			User03Icon,
			"User03Icon",
			"A neutral figure that lacks the carved base and abstraction.",
		),
		suggestion(
			User02Icon,
			"User02Icon",
			"Another compact figure treatment without carved-object cues.",
		),
	],
	"ritual-implement": [
		suggestion(
			GlassWaterIcon,
			"GlassWaterIcon",
			"Provides a coherent vessel, but lacks a goblet stem and ritual detail.",
		),
		suggestion(
			DrinkIcon,
			"DrinkIcon",
			"A handled ceremonial vessel with a more ordinary silhouette.",
		),
		suggestion(PotionIcon, "PotionIcon", "A fantasy vessel with the wrong ritual function."),
	],
	"wind-instrument": [
		suggestion(
			WhistleIcon,
			"WhistleIcon",
			"Directly matches a listed wind instrument, but is contemporary.",
		),
		suggestion(
			VolumeHighIcon,
			"VolumeHighIcon",
			"Communicates sound, but not a physical instrument.",
		),
		suggestion(
			MusicNote01Icon,
			"MusicNote01Icon",
			"Communicates music without identifying an instrument.",
		),
	],
	rune: [
		suggestion(
			TextSquareIcon,
			"TextSquareIcon",
			"Combines a mark and tile, but reads as typography.",
		),
		suggestion(
			Shapes01Icon,
			"Shapes01Icon",
			"Offers an angular glyph vocabulary, but no carved stone tile.",
		),
		suggestion(
			CodeSquareIcon,
			"CodeSquareIcon",
			"Places an angular mark in a tile, but reads as software.",
		),
	],
};

export const HUGE_ICON_MISSING_MARK = UnavailableIcon;
