export type AdminPermission = {
	allowed: boolean;
	expiresAt: string | null;
	override: "allow" | "deny" | "inherited";
	permission: string;
	source: string;
};
export type AdminFeedbackReply = {
	actorUserId: string | null;
	authorEmail: string;
	authorType: "admin" | "customer";
	createdAt: string;
	deliveryAttemptedAt: string | null;
	deliveryStatus: "delivered" | "failed" | "pending";
	id: string;
	message: string;
	source: "admin_page" | "email";
};
export type AdminFeedback = {
	accountType: "anonymous" | "registered" | null;
	category: "bug" | "general" | "idea";
	createdAt: string;
	customerReceiptStatus: "delivered" | "failed" | "pending";
	id: string;
	message: string;
	notificationStatus: "delivered" | "failed" | "pending";
	replyCount: number;
	replyEmail: string;
	status: "new" | "open" | "replied";
	subject: string;
	username: string | null;
};
export type AdminFeedbackDetail = AdminFeedback & {
	actorUserId: string | null;
	notificationAttemptedAt: string | null;
	page: string | null;
	replies: AdminFeedbackReply[];
	viewedAt: string | null;
};
export type AdminPublication = {
	id: string;
	slug: string;
	status: "published" | "unpublished" | "suspended";
	visibility: "listed" | "unlisted";
	title: string;
	summary: string;
	worldId: string;
	ownerUserId: string;
	ownerName: string | null;
	ownerUsername: string;
	release: {id: string; number: number; publishedAt: string};
};
export type AdminPlaythrough = {
	id: string;
	publicationId: string;
	publicationTitle: string;
	publicationSlug: string;
	releaseId: string;
	releaseNumber: number;
	playerReference: string;
	status: "active" | "completed" | "abandoned" | "errored";
	commandCount: number;
	startedAt: string;
	lastActivityAt: string;
	endedAt: string | null;
	anonymizedAt: string | null;
	purgeAfter: string | null;
};
export type AdminWorld = {
	createdAt: string;
	deletedAt: string | null;
	editorSlug: string | null;
	id: string;
	lifecycle: "active" | "trashed";
	name: string;
	owner: {
		accountType: "anonymous" | "registered";
		displayName: string | null;
		id: string;
		username: string | null;
	};
	revision: number;
	schemaVersion: number;
	trashPurgeAfter: string | null;
	updatedAt: string;
	worldSizeBytes: number;
};
export type AdminUser = {
	accountType: "anonymous" | "registered";
	cleanupAfter: string | null;
	cleanupReason: string | null;
	cleanupScheduledAt: string | null;
	createdAt: string;
	displayName: string | null;
	id: string;
	lastSeenAt: string;
	maxWorlds: number;
	siteRole: "admin" | "user";
	status: "active" | "deleted" | "suspended";
	suspendedAt: string | null;
	suspensionReason: string | null;
	trashedWorldCount: number;
	username: string | null;
	worldCount: number;
};
export type AdminUserDetail = AdminUser & {
	credentialChangedAt: string | null;
	email: string | null;
	emailVerifiedAt: string | null;
	mfaEnrolled: boolean;
	permissions: AdminPermission[];
	registeredAt: string | null;
	verificationPending: boolean;
	sessions: Array<{
		audience: "admin" | "editor" | "play";
		createdAt: string;
		expiresAt: string;
		id: string;
		lastSeenAt: string;
		revokedAt: string | null;
	}>;
	worlds: AdminWorld[];
};
